#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     seeker,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     pivotMotor,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontRight,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     frontLeft,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void motorControl() {
	int threshold = 10;
	int leftPower = 0, rightPower = 0, pivotPower = 0;
	int power = joystick.joy1_y1;
	pivotPower = joystick.joy1_x2;
	if(pivotPower > threshold || pivotPower < -threshold) {
		motor[pivotMotor] = pivotPower;
		if(pivotPower > threshold) {
			rightPower = pivotPower;
			leftPower = -pivotPower;
		} else if(pivotPower < -threshold) {
			leftPower = pivotPower;
			rightPower = -pivotPower;
		}
	}

	if(power > threshold) {
		if(leftPower < 0) {
			leftPower -= power;
			rightPower += power;
		} else if(leftPower > 0) {
			leftPower += power;
			rightPower -= power;
		}
	} else if(power < -threshold) {
		if(leftPower < 0) {
			leftPower += power;
			rightPower -= power;
		} else if(leftPower > 0) {
			leftPower -= power;
			rightPower += power;
		}
	}
	motor[frontRight] = rightPower;
	motor[frontLeft] = leftPower;
}

task main()
{
	while(true) {
		motorControl();
	}
}
