#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     elevatorMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
task main()
{
	if(joy1Btn(1)){
		motor[elevatorMotor] = 100;
	}
	if(joy1Btn(2)){
		motor[elevatorMotor] = -100;
	}
	else{
		motor[elevatorMotor] = 0;
	}

}
